name: Create pr
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  create-pr:
    if: ${{ github.event.pull_request.title == 'feat add src/hello.md'}}
    permissions:
      actions: write
      checks: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - uses: actions/checkout@v3
      - run: source sh/check-pr.sh
