name: Create repository
on:
  push:
    branches:
      - main
      - master

jobs:
  create-repository:
    permissions:
      actions: write
      checks: write
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.run_number == 1}}
        run: |
          mv docs/README/README-2.md README.md
          git config user.name  "github actions"
          git config user.email "actions@example.com"
          git add .
          git commit -m "update to README-2.md"
          git push
